# Numpy with Python Basics

In [1]:
import numpy as np

In [2]:
x = 4

In [3]:
y = 'apple'

In [4]:
print(x)

4


In [5]:
print(y)

apple


In [10]:
L = list(range(10))

In [9]:
print(L)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
type(L[0])

int

In [13]:
L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [14]:
import numpy as np

Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point)

In [15]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

unlike Python lists, NumPy arrays can explicitly be multi-dimensional

In [17]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Arrays from Scratch

In [18]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [21]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.random.random((3, 3))

array([[0.10179065, 0.86636108, 0.26779585],
       [0.78204247, 0.59954266, 0.05707108],
       [0.53727332, 0.07461948, 0.6897974 ]])

In [36]:
a = np.random.normal(0, 1, (3, 3))

In [37]:
np.mean(a)

0.1840109583089964

In [38]:
np.var(a)

1.0714376678810555

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [113]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [61]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Array Indexing: Accessing Single Elements

In [62]:
x1

array([5, 0, 3, 3, 7, 9])

In [64]:
x1[4]

7

In [65]:
x1[-1]

9

In [66]:
x1[-3]

3

Array Slicing: Accessing Subarrays

In [68]:
x = np.arange(10)

In [69]:
x[:5]  # first five elements


array([0, 1, 2, 3, 4])

In [70]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [71]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [72]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [73]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [74]:
print(x2[:, 0])  # first column of x2

[3 7 1]


In [75]:
print(x2[0, :])  # first row of x2

[3 5 2 4]


In [76]:
print(x2[0])  # equivalent to x2[0, :]

[3 5 2 4]


Reshaping of Arrays

In [77]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
x = np.array([1, 2, 3])

In [79]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

Array Concatenation and Splitting

In [81]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [87]:
np.concatenate([x, y],0)

array([1, 2, 3, 3, 2, 1])

In [92]:
np.stack([x,y])

array([[1, 2, 3],
       [3, 2, 1]])

Splitting of arrays

In [93]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [94]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [95]:
x

array([0, 1, 2, 3])

In [96]:
np.add(x, 2)

array([2, 3, 4, 5])

Absolute value


In [97]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [98]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [100]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("ln(x)    =", np.log(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))


x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
ln(x)    = [0.         0.69314718 1.09861229]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [101]:
np.add.accumulate(x)

array([1, 3, 6])

In [102]:
L = np.random.random(100)
sum(L)

50.06127402202757

In [103]:
np.sum(L)

50.061274022027575

In [104]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

66.2 ms ± 324 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
347 µs ± 2.38 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [105]:
min(big_array), max(big_array)

(6.902627726068644e-07, 0.9999980378239232)

In [107]:
M = np.random.random((3, 4))
print(M)

[[5.06233442e-04 6.99915598e-01 2.00568228e-01 8.69877243e-01]
 [2.31541943e-01 3.80869753e-01 7.06367442e-02 7.54470808e-01]
 [4.36632905e-01 5.55443154e-01 4.27299967e-01 3.54597159e-01]]


In [108]:
M.min(axis=0) # find the minimum value within each column

array([0.00050623, 0.38086975, 0.07063674, 0.35459716])

In [109]:
M.min(axis=1) # find the minimum value within each row

array([0.00050623, 0.07063674, 0.35459716])

In [110]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [111]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [122]:
#sorted version of the array without modifying the input
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [123]:
#sort the array in-place
x.sort()
print(x)

[1 2 3 4 5]


In [126]:
# sort each column of X
np.sort(x2, axis=0)

array([[1, 5, 2, 4],
       [3, 6, 7, 7],
       [7, 6, 8, 8]])

In [127]:
np.sort(x2, axis=1)

array([[2, 3, 4, 5],
       [6, 7, 8, 8],
       [1, 6, 7, 7]])

Structured Data: NumPy's Structured Arrays

In [138]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [139]:
# Here 'U10' translates to "Unicode string of maximum length 10
# 'i4' translates to "4-byte (i.e., 32 bit) integer,"
# 'f8' translates to "8-byte (i.e., 64 bit) float."
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [140]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [141]:
data[0]

('Alice', 25, 55.)

In [142]:
# Get names where age is under 30
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')